# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73e5323b205f97e1425e6b155d8ee6351745c92d6a057c5f718b00084cbdd59fb4d7b02598ff28bc331ab93dbea7de8812b2fb98eb27ea88ba332d6463936a93

test:
  secret_key_base: 2dfa67e59f957ea8acf6857bd5ecd158b76ed0953dff861a1f3696272f38c8e9790399f4fb7eb9aead28d20d48324ede032af3f800f49fb0fbbf2c34faa7eb52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
